name = basic_machines
<<<<<<< HEAD
description = adding basic machines
depends = default
optional_depends = moreores, protector, areas, boneworld
min_minetest_version = 5.1
=======
depends = default
optional_depends = protector,doors,areas,boneworld,moreores,mesecons
description = automate gameplay with machines. build logic mechanisms.
>>>>>>> 56164fb61a20a5ed0314feb18c69cbf0a172a37b
